name: 'coalesce_data_quality_workshop_2025'
version: '1.0.0'
config-version: 2

profile: 'dbt_data_quality_workshop'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: 
  - "target"
  - "dbt_packages"


models:
  coalesce_data_quality_workshop_2025:
    marts:
      +materialized: table
