version: 2

models:
  - name: customer_lifetime_values
    description: >
      This model calculates the lifetime value of customers by aggregating
      their order history and classifying them as new or returning customers. It provides
      insights into customer spending behavior and order patterns.
    columns:
      - name: customer_id
        description: A unique identifier for each customer.
        tests:
          - not_null
          - unique
          - generic_great_than

      - name: customer_name
        description: The full name of the customer.

      - name: customer_email
        description: The email address of the customer.

      - name: customer_type
        description: >
          Indicates whether the customer is new or returning based on their
          order history.

      - name: total_orders
        description: The total number of orders placed by the customer.
        data_tests:
          - not_null

      - name: total_gross_spend
        description: The total gross amount spent by the customer across all orders.
        data_tests:
          - not_null

      - name: total_net_spend
        description: The total net amount spent by the customer after discounts and returns.
        data_tests:
          - not_null

      - name: total_tax_paid
        description: The total amount of tax paid by the customer across all orders.
        data_tests:
          - not_null
      - name: earliest_order_at
        description: The timestamp of the customer's first order.
        data_tests:
          - not_null

      - name: latest_order_at
        description: The timestamp of the customer's most recent order.
        data_tests:
          - not_null